### ISSUE TITLE
Add a demo to demonstrate use of LazyColumns

### ISSUE THREAD

**Issue by RitwikSingh28** [SrijanShovit/Compose-Camp-Sessions#3]
@SrijanShovit 
For Session 4, I intend to add a mini-project containing one activity, which demonstrates the use of LazyColumns taught during the Compose Camp. 

Screenshot : 
![Sample1](https://user-images.githubusercontent.com/106133014/197381003-93c0d703-8dcd-47ec-8a1f-fae175e08c4f.jpeg)
![Sample2](https://user-images.githubusercontent.com/106133014/197381009-8ce59cbd-b7f0-4c86-92b9-347a24e55cc5.jpeg)

**Comment by SrijanShovit** [comment]
Nice
Make a pr of it @RitwikSingh28 
Will merge it.
